namespace Test.XUnit
{
    using System.Collections.Generic;

    /// <summary>
    /// Static xUnit member-data for shared legacy coverage parity cases.
    /// </summary>
    public static class LegacyCoverageParityData
    {
        /// <summary>
        /// Enumerates shared legacy coverage case names.
        /// </summary>
        public static IEnumerable<object[]> Cases
        {
            get
            {
                yield return new object[] { "Alt-Svc End-To-End - HTTP/1.1 Response Header" };
                yield return new object[] { "Alt-Svc End-To-End - HTTP/2 Response Header" };
                yield return new object[] { "Alt-Svc End-To-End - HTTP/3 Response Header" };
                yield return new object[] { "Alt-Svc Header - Explicit Authority Format" };
                yield return new object[] { "Alt-Svc Header - Same Authority Format" };
                yield return new object[] { "CancellationToken - New Instance After Dispose" };
                yield return new object[] { "CancellationToken - Per-Instance Isolation" };
                yield return new object[] { "Chunk Data Integrity - Binary Data" };
                yield return new object[] { "Chunk Data Integrity - Unicode Data" };
                yield return new object[] { "Chunked - Chunk Extension Metadata" };
                yield return new object[] { "Chunked - Immediate Final Chunk (Zero Length)" };
                yield return new object[] { "Chunked - Single Chunk Then Final" };
                yield return new object[] { "Header Parsing - Colon In Value Preserved (Lite)" };
                yield return new object[] { "HPACK - Dynamic Table Size Shrink Evicts Indexed Entry" };
                yield return new object[] { "HPACK - Dynamic Table Size Update Exceeding Limit Rejected" };
                yield return new object[] { "HPACK - Huffman String Accepted" };
                yield return new object[] { "HTTP/1 Chunk Reader - Data Then Final Chunk" };
                yield return new object[] { "HTTP/1 Parser - Absolute URI Request Line" };
                yield return new object[] { "HTTP/1 Parser - Streaming SHA256 Marks Chunked" };
                yield return new object[] { "HTTP/1.1 TLS Transport - Chunked SSE Wire" };
                yield return new object[] { "HTTP/1.1 TLS Transport - HttpClient GET" };
                yield return new object[] { "HTTP/1.1 TLS Transport - Raw GET And ALPN" };
                yield return new object[] { "HTTP/2 Frame - GoAway Roundtrip" };
                yield return new object[] { "HTTP/2 Frame - Ping Roundtrip" };
                yield return new object[] { "HTTP/2 Frame - Raw Roundtrip" };
                yield return new object[] { "HTTP/2 Frame - RstStream Roundtrip" };
                yield return new object[] { "HTTP/2 Frame - Settings Ack Must Be Empty" };
                yield return new object[] { "HTTP/2 Frame - WindowUpdate Roundtrip" };
                yield return new object[] { "HTTP/2 h2c Transport - Chunked API Response" };
                yield return new object[] { "HTTP/2 h2c Transport - Concurrent Streams Complete Independently" };
                yield return new object[] { "HTTP/2 h2c Transport - Connection Header Triggers GoAway" };
                yield return new object[] { "HTTP/2 h2c Transport - Content-Length Mismatch Triggers GoAway" };
                yield return new object[] { "HTTP/2 h2c Transport - Continuation Header Block Routes" };
                yield return new object[] { "HTTP/2 h2c Transport - Dynamic Table Indexed Header Reuse" };
                yield return new object[] { "HTTP/2 h2c Transport - HTTP/1 Request Rejected" };
                yield return new object[] { "HTTP/2 h2c Transport - Huffman Authority Header Routes" };
                yield return new object[] { "HTTP/2 h2c Transport - Idle Data Triggers GoAway" };
                yield return new object[] { "HTTP/2 h2c Transport - Idle Timeout Sends GoAway [slow]" };
                yield return new object[] { "HTTP/2 h2c Transport - Invalid TE Header Triggers GoAway" };
                yield return new object[] { "HTTP/2 h2c Transport - Invalid Trailer PseudoHeader Triggers GoAway" };
                yield return new object[] { "HTTP/2 h2c Transport - MaxConcurrentStreams Refuses Excess Stream [slow]" };
                yield return new object[] { "HTTP/2 h2c Transport - Oversized Header Table Update Triggers GoAway" };
                yield return new object[] { "HTTP/2 h2c Transport - Padded Priority Headers And Data Route" };
                yield return new object[] { "HTTP/2 h2c Transport - Peer MaxFrameSize Splits Response Frames" };
                yield return new object[] { "HTTP/2 h2c Transport - POST Body Echo" };
                yield return new object[] { "HTTP/2 h2c Transport - Request Flow Control Violation Triggers GoAway" };
                yield return new object[] { "HTTP/2 h2c Transport - Request Trailers Routed" };
                yield return new object[] { "HTTP/2 h2c Transport - Response Flow Control WindowUpdate" };
                yield return new object[] { "HTTP/2 h2c Transport - Response Trailers" };
                yield return new object[] { "HTTP/2 h2c Transport - Routed GET Response" };
                yield return new object[] { "HTTP/2 h2c Transport - Settings And Ping" };
                yield return new object[] { "HTTP/2 h2c Transport - Sibling Stream Survives RstStream Cancellation" };
                yield return new object[] { "HTTP/2 h2c Transport - SSE API Response" };
                yield return new object[] { "HTTP/2 Handshake - First Frame Must Be Settings" };
                yield return new object[] { "HTTP/2 Handshake - First Settings Must Not Be Ack" };
                yield return new object[] { "HTTP/2 Handshake - Preface And Settings Parsed" };
                yield return new object[] { "HTTP/2 Preface - Exact Bytes Roundtrip" };
                yield return new object[] { "HTTP/2 Preface - Invalid Bytes Rejected" };
                yield return new object[] { "HTTP/2 Settings - Invalid EnablePush Rejected" };
                yield return new object[] { "HTTP/2 Settings - Invalid MaxFrameSize Rejected" };
                yield return new object[] { "HTTP/2 Settings - Invalid Payload Length Rejected" };
                yield return new object[] { "HTTP/2 Settings - Payload Roundtrip" };
                yield return new object[] { "HTTP/2 Stream State - Inbound Then Outbound Lifecycle" };
                yield return new object[] { "HTTP/2 Stream State - Invalid Data On Idle Rejected" };
                yield return new object[] { "HTTP/2 Stream State - Outbound Then Inbound Lifecycle" };
                yield return new object[] { "HTTP/2 Stream State - Reset Closes Stream" };
                yield return new object[] { "HTTP/2 Stream State - Trailer Completion Closes Stream" };
                yield return new object[] { "HTTP/2 Validation - Cleartext Prior Knowledge Allowed When Supported" };
                yield return new object[] { "HTTP/2 Writer - Concurrent Writes Preserve Frames" };
                yield return new object[] { "HTTP/3 Control Stream - Missing Settings Rejected" };
                yield return new object[] { "HTTP/3 Control Stream - NonControl Type Rejected" };
                yield return new object[] { "HTTP/3 Control Stream - Settings Roundtrip" };
                yield return new object[] { "HTTP/3 Frame - GoAway Roundtrip" };
                yield return new object[] { "HTTP/3 Frame - Settings Roundtrip" };
                yield return new object[] { "HTTP/3 Frame - Truncated Payload Rejected" };
                yield return new object[] { "HTTP/3 Message - Data After Trailers Rejected" };
                yield return new object[] { "HTTP/3 Message - Data Before Headers Rejected" };
                yield return new object[] { "HTTP/3 Message - Headers Body Trailers Roundtrip" };
                yield return new object[] { "HTTP/3 QUIC Transport - Chunked API Response" };
                yield return new object[] { "HTTP/3 QUIC Transport - Concurrent Streams Complete Independently" };
                yield return new object[] { "HTTP/3 QUIC Transport - Connection Header Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - Control Stream And Routed GET" };
                yield return new object[] { "HTTP/3 QUIC Transport - Duplicate Authority PseudoHeader Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - Duplicate Control Stream Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - Duplicate Method PseudoHeader Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - Duplicate Path PseudoHeader Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - Duplicate QPACK Decoder Stream Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - Duplicate QPACK Encoder Stream Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - Duplicate Scheme PseudoHeader Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - Dynamic NameReference Qpack Header Block Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - Dynamic Qpack Header Block Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - Empty Trailer Name Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - Graceful Stop Drains InFlight Stream [slow]" };
                yield return new object[] { "HTTP/3 QUIC Transport - Graceful Stop Rejects New Stream After GoAway [slow]" };
                yield return new object[] { "HTTP/3 QUIC Transport - Idle Timeout Sends GoAway [slow]" };
                yield return new object[] { "HTTP/3 QUIC Transport - Invalid TE Header Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - Invalid Trailer PseudoHeader Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - MaxConcurrentStreams Blocks Excess Stream Until Capacity Available [slow]" };
                yield return new object[] { "HTTP/3 QUIC Transport - Missing Method PseudoHeader Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - Missing Path PseudoHeader Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - Missing Scheme PseudoHeader Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - NeverIndexed Qpack Header Block Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - Oversized Body Closes Connection [slow]" };
                yield return new object[] { "HTTP/3 QUIC Transport - POST Body Echo" };
                yield return new object[] { "HTTP/3 QUIC Transport - PseudoHeader After Regular Header Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - QPACK Prefix Header Block Routes Request" };
                yield return new object[] { "HTTP/3 QUIC Transport - Relative Path Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - Request Trailers Routed" };
                yield return new object[] { "HTTP/3 QUIC Transport - SSE And Trailers" };
                yield return new object[] { "HTTP/3 QUIC Transport - Trailer ContentLength Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - Unsupported PseudoHeader Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - Uppercase Header Name Closes Connection" };
                yield return new object[] { "HTTP/3 QUIC Transport - Uppercase Trailer Name Closes Connection" };
                yield return new object[] { "HTTP/3 Runtime Detection - Matches QuicListener Reflection" };
                yield return new object[] { "HTTP/3 Runtime Detection - Returns Structured Result" };
                yield return new object[] { "HTTP/3 Runtime Normalization - Disables Http3 And AltSvc When Unavailable" };
                yield return new object[] { "HTTP/3 Runtime Normalization - Leaves Supported Configuration Intact" };
                yield return new object[] { "HTTP/3 Settings - Duplicate Identifier Rejected" };
                yield return new object[] { "HTTP/3 Settings - Payload Roundtrip" };
                yield return new object[] { "HTTP/3 VarInt - Boundary Roundtrip" };
                yield return new object[] { "HTTP/3 VarInt - Truncated Value Rejected" };
                yield return new object[] { "IDisposable - Context Disposes TokenSource" };
                yield return new object[] { "IDisposable - Double Dispose Safe" };
                yield return new object[] { "Malformed - Chunked With Content-Length" };
                yield return new object[] { "Malformed - Conflicting Duplicate Content-Length" };
                yield return new object[] { "Malformed - Duplicate Host Header" };
                yield return new object[] { "Malformed - Empty Request Header" };
                yield return new object[] { "Malformed - Header Key With No Value" };
                yield return new object[] { "Malformed - Incomplete Request Line" };
                yield return new object[] { "Malformed - Negative Content-Length" };
                yield return new object[] { "Malformed - Non-Numeric Content-Length" };
                yield return new object[] { "Malformed - Null Stream" };
                yield return new object[] { "Malformed - Obsolete Folded Header" };
                yield return new object[] { "Malformed - Request Line Only (No Headers)" };
                yield return new object[] { "Malformed - Truncated Content-Length Body" };
                yield return new object[] { "Malformed - Very Long Header Value (64KB)" };
                yield return new object[] { "MaxHeaderCount - Disabled With Zero" };
                yield return new object[] { "MaxHeaderCount - Lite Allows Within Limit" };
                yield return new object[] { "MaxHeaderCount - Lite Rejects Too Many Headers" };
                yield return new object[] { "MaxRequestBodySize - Disabled With Zero" };
                yield return new object[] { "MaxRequestBodySize - Lite Allows Within Limit" };
                yield return new object[] { "MaxRequestBodySize - Lite Rejects Oversized Body" };
                yield return new object[] { "QPACK - Dynamic Reference Rejected" };
                yield return new object[] { "QPACK - Huffman String Accepted" };
                yield return new object[] { "QPACK - Static And Literal Roundtrip" };
                yield return new object[] { "QueryDetails - Caching Returns Same Instance Per Object" };
                yield return new object[] { "QueryDetails - Elements Caching" };
                yield return new object[] { "QueryDetails - Empty Query String" };
                yield return new object[] { "QueryDetails - Key Only (No Value)" };
                yield return new object[] { "QueryDetails - Multiple Same Keys" };
                yield return new object[] { "QueryDetails - No Query String" };
                yield return new object[] { "RFC 6455 - Server-Sent Events Format" };
                yield return new object[] { "RFC 7230 - Chunked Request Tested via Server Tests" };
                yield return new object[] { "RFC 7230 - ChunkedTransfer Flag Set on Lite Request" };
                yield return new object[] { "Settings - MaxHeaderCount Configurable" };
                yield return new object[] { "Settings - MaxHeaderCount Default" };
                yield return new object[] { "Settings - MaxHeaderCount Disable With Zero" };
                yield return new object[] { "Settings - MaxRequestBodySize Configurable" };
                yield return new object[] { "Settings - MaxRequestBodySize Default" };
                yield return new object[] { "Settings - MaxRequestBodySize Disable With Negative" };
                yield return new object[] { "Settings - MaxRequestBodySize Disable With Zero" };
                yield return new object[] { "SSE Format - Chunked Transport Compliance" };
                yield return new object[] { "SSE Format - Data Field Compliance" };
                yield return new object[] { "UrlDetails - Elements Decodes Percent Encoding" };
                yield return new object[] { "UrlDetails - Elements With Trailing Slash" };
                yield return new object[] { "UrlDetails - RawWithoutQuery Strips Query" };
                yield return new object[] { "WatsonWebserver - Authentication Failure (No Token)" };
                yield return new object[] { "WatsonWebserver - Binary Chunked Request Body" };
                yield return new object[] { "WatsonWebserver - Chunked Encoding Edge Cases" };
                yield return new object[] { "WatsonWebserver - Chunked Request Body (DataAsBytes)" };
                yield return new object[] { "WatsonWebserver - Chunked Request Body (DataAsString)" };
                yield return new object[] { "WatsonWebserver - Chunked Request Body (Manual ReadChunk)" };
                yield return new object[] { "WatsonWebserver - Chunked Request Body (ReadBodyAsync)" };
                yield return new object[] { "WatsonWebserver - Chunked Transfer Encoding [slow]" };
                yield return new object[] { "WatsonWebserver - Concurrent Requests (10)" };
                yield return new object[] { "WatsonWebserver - Content Route" };
                yield return new object[] { "WatsonWebserver - Content Route Directory Traversal" };
                yield return new object[] { "WatsonWebserver - Content Route With Query String" };
                yield return new object[] { "WatsonWebserver - Content-Length Mismatch (under)" };
                yield return new object[] { "WatsonWebserver - Data Preservation (hello)" };
                yield return new object[] { "WatsonWebserver - Data Preservation (hello\\r\\n)" };
                yield return new object[] { "WatsonWebserver - Deep Nonexistent Path" };
                yield return new object[] { "WatsonWebserver - Default Route" };
                yield return new object[] { "WatsonWebserver - DELETE Request" };
                yield return new object[] { "WatsonWebserver - DELETE With No Body" };
                yield return new object[] { "WatsonWebserver - Directory Traversal (Backslash)" };
                yield return new object[] { "WatsonWebserver - Directory Traversal (Deep)" };
                yield return new object[] { "WatsonWebserver - Directory Traversal (Encoded)" };
                yield return new object[] { "WatsonWebserver - Documented Route in OpenAPI" };
                yield return new object[] { "WatsonWebserver - Double Send Response" };
                yield return new object[] { "WatsonWebserver - Dynamic Route (Regex)" };
                yield return new object[] { "WatsonWebserver - Empty Body POST" };
                yield return new object[] { "WatsonWebserver - Empty POST Body" };
                yield return new object[] { "WatsonWebserver - Exception In Route Handler" };
                yield return new object[] { "WatsonWebserver - GET Request" };
                yield return new object[] { "WatsonWebserver - HTTP/1.1 Keepalive After Chunked Request" };
                yield return new object[] { "WatsonWebserver - HTTP/1.1 Keepalive Sequential Requests" };
                yield return new object[] { "WatsonWebserver - HTTP/1.1 Raw Sad Path Chunked With Content-Length" };
                yield return new object[] { "WatsonWebserver - HTTP/1.1 Raw Sad Path Conflicting Content-Length" };
                yield return new object[] { "WatsonWebserver - HTTP/1.1 Raw Sad Path Duplicate Host Header" };
                yield return new object[] { "WatsonWebserver - HTTP/1.1 Raw Sad Path Invalid Chunk Size" };
                yield return new object[] { "WatsonWebserver - HTTP/1.1 Raw Sad Path Invalid Header Line" };
                yield return new object[] { "WatsonWebserver - HTTP/1.1 Raw Sad Path Malformed Request Line" };
                yield return new object[] { "WatsonWebserver - HTTP/1.1 Raw Sad Path Missing Chunk Terminator" };
                yield return new object[] { "WatsonWebserver - HTTP/1.1 Raw Sad Path Missing Host Header" };
                yield return new object[] { "WatsonWebserver - HTTP/1.1 Raw Sad Path Obsolete Folded Header" };
                yield return new object[] { "WatsonWebserver - HTTP/1.1 Raw Sad Path Truncated Chunk Body" };
                yield return new object[] { "WatsonWebserver - HTTP/1.1 Raw Sad Path Truncated Content-Length Body" };
                yield return new object[] { "WatsonWebserver - HTTP/1.1 Wire Chunked Request" };
                yield return new object[] { "WatsonWebserver - HTTP/1.1 Wire Chunked Response" };
                yield return new object[] { "WatsonWebserver - HTTP/1.1 Wire Normal Response" };
                yield return new object[] { "WatsonWebserver - HTTP/1.1 Wire SSE Response" };
                yield return new object[] { "WatsonWebserver - Large Chunked Request Body (64KB)" };
                yield return new object[] { "WatsonWebserver - Normal POST Regression (Content-Length)" };
                yield return new object[] { "WatsonWebserver - OpenAPI Documented Endpoint Works" };
                yield return new object[] { "WatsonWebserver - OpenAPI JSON Endpoint" };
                yield return new object[] { "WatsonWebserver - OpenAPI POST Endpoint" };
                yield return new object[] { "WatsonWebserver - OPTIONS Preflight" };
                yield return new object[] { "WatsonWebserver - Parameter Route" };
                yield return new object[] { "WatsonWebserver - POST Request" };
                yield return new object[] { "WatsonWebserver - Post-Authentication Route (Invalid)" };
                yield return new object[] { "WatsonWebserver - Post-Authentication Route (Valid)" };
                yield return new object[] { "WatsonWebserver - PostRouting Executes [slow]" };
                yield return new object[] { "WatsonWebserver - Pre-Authentication Route" };
                yield return new object[] { "WatsonWebserver - PUT Request" };
                yield return new object[] { "WatsonWebserver - Query Echo Route" };
                yield return new object[] { "WatsonWebserver - Rapid Sequential Requests (20)" };
                yield return new object[] { "WatsonWebserver - Request With Many Headers (50)" };
                yield return new object[] { "WatsonWebserver - Runtime Route Add" };
                yield return new object[] { "WatsonWebserver - Runtime Route Duplicate Add" };
                yield return new object[] { "WatsonWebserver - Runtime Route Remove" };
                yield return new object[] { "WatsonWebserver - Server-Sent Events [slow]" };
                yield return new object[] { "WatsonWebserver - SSE Edge Cases" };
                yield return new object[] { "WatsonWebserver - Static Route" };
                yield return new object[] { "WatsonWebserver - Swagger UI Endpoint" };
                yield return new object[] { "WatsonWebserver - Unrecognized HTTP Method" };
                yield return new object[] { "WatsonWebserver - Very Long URL" };
                yield return new object[] { "WatsonWebserver - Wrong Method (POST to GET route)" };
                yield return new object[] { "WatsonWebserver Secondary - Authentication Failure (No Token)" };
                yield return new object[] { "WatsonWebserver Secondary - Binary Chunked Request Body" };
                yield return new object[] { "WatsonWebserver Secondary - Chunked Encoding Edge Cases" };
                yield return new object[] { "WatsonWebserver Secondary - Chunked Request Body (DataAsBytes)" };
                yield return new object[] { "WatsonWebserver Secondary - Chunked Request Body (DataAsString)" };
                yield return new object[] { "WatsonWebserver Secondary - Chunked Request Body (Manual ReadChunk)" };
                yield return new object[] { "WatsonWebserver Secondary - Chunked Request Body (ReadBodyAsync)" };
                yield return new object[] { "WatsonWebserver Secondary - Chunked Transfer Encoding [slow]" };
                yield return new object[] { "WatsonWebserver Secondary - Concurrent Requests (10)" };
                yield return new object[] { "WatsonWebserver Secondary - Content Route" };
                yield return new object[] { "WatsonWebserver Secondary - Content Route Directory Traversal" };
                yield return new object[] { "WatsonWebserver Secondary - Content Route With Query String" };
                yield return new object[] { "WatsonWebserver Secondary - Content-Length Mismatch (under)" };
                yield return new object[] { "WatsonWebserver Secondary - Data Preservation (hello)" };
                yield return new object[] { "WatsonWebserver Secondary - Data Preservation (hello\\r\\n)" };
                yield return new object[] { "WatsonWebserver Secondary - Deep Nonexistent Path" };
                yield return new object[] { "WatsonWebserver Secondary - Default Route" };
                yield return new object[] { "WatsonWebserver Secondary - DELETE Request" };
                yield return new object[] { "WatsonWebserver Secondary - DELETE With No Body" };
                yield return new object[] { "WatsonWebserver Secondary - Directory Traversal (Backslash)" };
                yield return new object[] { "WatsonWebserver Secondary - Directory Traversal (Deep)" };
                yield return new object[] { "WatsonWebserver Secondary - Directory Traversal (Encoded)" };
                yield return new object[] { "WatsonWebserver Secondary - Documented Route in OpenAPI" };
                yield return new object[] { "WatsonWebserver Secondary - Double Send Response" };
                yield return new object[] { "WatsonWebserver Secondary - Dynamic Route (Regex)" };
                yield return new object[] { "WatsonWebserver Secondary - Empty Body POST" };
                yield return new object[] { "WatsonWebserver Secondary - Empty POST Body" };
                yield return new object[] { "WatsonWebserver Secondary - Exception In Route Handler" };
                yield return new object[] { "WatsonWebserver Secondary - GET Request" };
                yield return new object[] { "WatsonWebserver Secondary - Header With Colon In Value" };
                yield return new object[] { "WatsonWebserver Secondary - Header With URL Value" };
                yield return new object[] { "WatsonWebserver Secondary - HTTP/1.1 Raw Sad Path Chunked With Content-Length" };
                yield return new object[] { "WatsonWebserver Secondary - HTTP/1.1 Raw Sad Path Conflicting Content-Length" };
                yield return new object[] { "WatsonWebserver Secondary - HTTP/1.1 Raw Sad Path Duplicate Host Header" };
                yield return new object[] { "WatsonWebserver Secondary - HTTP/1.1 Raw Sad Path Invalid Chunk Size" };
                yield return new object[] { "WatsonWebserver Secondary - HTTP/1.1 Raw Sad Path Invalid Header Line" };
                yield return new object[] { "WatsonWebserver Secondary - HTTP/1.1 Raw Sad Path Malformed Request Line" };
                yield return new object[] { "WatsonWebserver Secondary - HTTP/1.1 Raw Sad Path Missing Chunk Terminator" };
                yield return new object[] { "WatsonWebserver Secondary - HTTP/1.1 Raw Sad Path Missing Host Header" };
                yield return new object[] { "WatsonWebserver Secondary - HTTP/1.1 Raw Sad Path Obsolete Folded Header" };
                yield return new object[] { "WatsonWebserver Secondary - HTTP/1.1 Raw Sad Path Truncated Chunk Body" };
                yield return new object[] { "WatsonWebserver Secondary - HTTP/1.1 Raw Sad Path Truncated Content-Length Body" };
                yield return new object[] { "WatsonWebserver Secondary - HTTP/1.1 Wire Chunked Request" };
                yield return new object[] { "WatsonWebserver Secondary - HTTP/1.1 Wire Chunked Response" };
                yield return new object[] { "WatsonWebserver Secondary - HTTP/1.1 Wire Normal Response" };
                yield return new object[] { "WatsonWebserver Secondary - HTTP/1.1 Wire SSE Response" };
                yield return new object[] { "WatsonWebserver Secondary - Large Chunked Request Body (64KB)" };
                yield return new object[] { "WatsonWebserver Secondary - Malformed Range Header (bytes=0--1)" };
                yield return new object[] { "WatsonWebserver Secondary - Normal POST Regression (Content-Length)" };
                yield return new object[] { "WatsonWebserver Secondary - OpenAPI Documented Endpoint Works" };
                yield return new object[] { "WatsonWebserver Secondary - OpenAPI JSON Endpoint" };
                yield return new object[] { "WatsonWebserver Secondary - OpenAPI POST Endpoint" };
                yield return new object[] { "WatsonWebserver Secondary - OPTIONS Preflight" };
                yield return new object[] { "WatsonWebserver Secondary - Parameter Route" };
                yield return new object[] { "WatsonWebserver Secondary - POST Request" };
                yield return new object[] { "WatsonWebserver Secondary - Post-Authentication Route (Invalid)" };
                yield return new object[] { "WatsonWebserver Secondary - Post-Authentication Route (Valid)" };
                yield return new object[] { "WatsonWebserver Secondary - PostRouting Executes [slow]" };
                yield return new object[] { "WatsonWebserver Secondary - Pre-Authentication Route" };
                yield return new object[] { "WatsonWebserver Secondary - PUT Request" };
                yield return new object[] { "WatsonWebserver Secondary - Query Echo Route" };
                yield return new object[] { "WatsonWebserver Secondary - Rapid Sequential Requests (20)" };
                yield return new object[] { "WatsonWebserver Secondary - Request With Many Headers (50)" };
                yield return new object[] { "WatsonWebserver Secondary - Runtime Route Add" };
                yield return new object[] { "WatsonWebserver Secondary - Runtime Route Duplicate Add" };
                yield return new object[] { "WatsonWebserver Secondary - Runtime Route Remove" };
                yield return new object[] { "WatsonWebserver Secondary - Server-Sent Events [slow]" };
                yield return new object[] { "WatsonWebserver Secondary - SSE Edge Cases" };
                yield return new object[] { "WatsonWebserver Secondary - Static Route" };
                yield return new object[] { "WatsonWebserver Secondary - Swagger UI Endpoint" };
                yield return new object[] { "WatsonWebserver Secondary - Unrecognized HTTP Method" };
                yield return new object[] { "WatsonWebserver Secondary - Very Long URL" };
                yield return new object[] { "WatsonWebserver Secondary - Wrong Method (POST to GET route)" };
            }
        }
    }
}

