<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Touchstone.Core" Version="0.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WatsonWebserver\WatsonWebserver.csproj" />
    <ProjectReference Include="..\Watson.Clients\Watson.Clients.csproj" />
  </ItemGroup>

</Project>
